### ISSUE TITLE
Spurious "missing field" error

### ISSUE THREAD

**Issue by protz** [CatalaLang/catala#107]
```
[ERROR] Missing field for structure Fine: "max_fine"
[ERROR] 
[ERROR]    --> ../291-11-6.catala_en
[ERROR]     | 
[ERROR]  99 |     (Fine content (Fine {
[ERROR]     |                    ^^^^^
[ERROR] 100 |       -- min_fine: $ 45
[ERROR]     |       ^^^^^^^^^^^^^^^^^
[ERROR] 101 |       -- max_fine: $ 45
[ERROR]     |       ^^^^^^^^^^^^^^^^^
[ERROR] 102 |     }));
[ERROR]     |     ^^
[ERROR]     + Definitions shared across all statutes
[ERROR]     +-+ 291-11.6 Mandatory use of seat belts, when, penalty
```
I am not sure what is causing this error, but the idea is that the `Fine` (for the record) already resolves to a particular record definition, so from there on, the pseudo-expression between the curly-braces should have its fields entirely determined by `Fine`, assuming `Fine` is properly resolved

**Comment by denismerigoux** [comment]
Ok so first of all this issue is caused by this line https://github.com/lfo-calculator/hawaii/blob/32f9f4c085f099d1114ee89c12f0ec5a42cfa680/catala-regs/291-11-6.catala_en#L3

This line includes `definitions` one time, but the line after includes it transitively once again so all the types in `definitions` are defined twice as a result. Nevertheless, this should not cause the bug you're seeing so I'll continue investigations.

**Comment by msprotz** [comment]
ah probably there's an environment issue where one part of the code sees the shadowed definition and another part doesn't -- I'll try to switch to the "master file" style you proposed and hopefully that'll fix the issue

**Comment by denismerigoux** [comment]
The commit above should fix this behavior, the check preventing multiple declarations of types with the same name was buggy.
