### ISSUE TITLE
Example Unit Tests Failing to parse on stable catala

### ISSUE THREAD

**Issue by QuantamHD** [CatalaLang/catala#125]
Should the opam version of Catala be bumped since the tests in this repo don't pass with 0.2.0 version?

catala version 0.2.0

```
ethanmoon@ethanmoon:~/catala/examples$ make CATALA=catala
[ERROR] Syntax error at token "```catala"
[ERROR] Message: expected an article title, another heading or some text
[ERROR] 
[ERROR] Error token:
[ERROR]  --> tests/test_tutorial.catala_en
[ERROR]   | 
[ERROR] 5 | ```catala
[ERROR]   | ^^^^^^^^^
[ERROR]   + 
[ERROR] 
[ERROR] Last good token:
[ERROR]  --> tests/test_tutorial.catala_en
[ERROR]   | 
[ERROR] 3 | ## Test
[ERROR]   | ^^^^^^
[ERROR] 4 | 
[ERROR]   | 
[ERROR] 5 | ```catala
[ERROR]   | ^
[ERROR]   + 
make[1]: *** [../Makefile.common.mk:19: tests/test_tutorial.run] Error 1
FAIL tutorial_en.test_tutorial.UnitTest1.run
make: *** [Makefile:26: tutorial_en.test_tutorial.UnitTest1.run] Error 1
```

**Comment by denismerigoux** [comment]
Hi @QuantamHD, thanks for reporting this issue ! Indeed, the `opam` version 0.2.0 of Catala is lagging many features. Many things have been improved other the last few months, and it's time for a new release. In the meantime, you can use 

    opam pin add catala --dev-repo

to locally pin your `catala` package to the latest commit in `master` instead of the old version in the `opam` repository.

**Comment by QuantamHD** [comment]
Thanks for the tip @denismerigoux.

The pin did fix the issue. Thanks for working on such cool software.

**Comment by EmileRolley** [comment]
I think this issue could be closed. Am I right @denismerigoux?
