### ISSUE TITLE
Tutorial revamping

### ISSUE THREAD

**Issue by denismerigoux** [CatalaLang/catala#172]
The current tutorial is neither complete nor up to date with current Catala features. I'm going to take some time revamping it, but I want your feedback! Please comment here to tell me:

* Is the current style of the tutorial where I run a thread about a fictitious tax system good or bad ?
* What are things that you would expect from the tutorial that are not in there currently ?
* Are there passages of the tutorial that are not useful ?
* In which order would you have the concepts of Catala introduced ? Is the current order good or bad ?

The current tutorial is here:
- Web version : https://catala-lang.org/en/examples/tutorial
- Code version : https://github.com/CatalaLang/catala/blob/master/examples/tutorial_en/tutorial_en.catala_en

**Comment by EmileRolley** [comment]
Hi @denismerigoux,

> * Is the current style of the tutorial where I run a thread about a fictitious tax system good or bad ?

I think it's a good idea to explain the workflow simultaneously of the syntax.

> * What are things that you would expect from the tutorial that are not in there currently ?

Adding commands to execute code examples could be useful to quick start tinkering and interpreting the code while reading the tutorial. More generally, adding a preamble explaining how to setup the dev environment and the basic usage of the compiler could make it easier to get started.

Another good thing could be to add a link for each introduced concept targeting an exhaustive documentation listing the entire Catala syntax -- which is missing at the moment.

> * Are there passages of the tutorial that are not useful ?

I don't feel like there are extra parts.

> * In which order would you have the concepts of Catala introduced ? Is the current order good or bad ?

The current sequence seems to me fluid and coherent.

**Comment by rmonat** [comment]
I read the tutorial a few days back and have a few comments on its current shape:
- line 97, I find that the declaration of the number of children in the `Individual` declaration structure comes a bit out of the blue at this point. Since you also speak about tax credits for children afterwards, I guess you could add a general sentence in the beginning saying that the tax system will also take into account the number of children in the household? 
- is the suffix $ for money manipulation in english and € in French?
- out of curiosity, why are conditions different (in the surface) from booleans?
- In the "fixing the computation" paragraph: I guess the comment lines 474-476 could be moved into the text of the tutorial (I would find it a bit more readable).

> Is the current style of the tutorial where I run a thread about a fictitious tax system good or bad ?
I think it's a good example. 

> Are there passages of the tutorial that are not useful ?
"Catala values" at the end could be moved to a documentation of the language.

> In which order would you have the concepts of Catala introduced? Is the current order good or bad?
I find the current order coherent.

**Comment by denismerigoux** [comment]
Thanks Raphaël! Fixed by https://github.com/CatalaLang/catala/commit/c51ea499623e228c72d6105c9377b8f2498514cf
