### ISSUE TITLE
Extract runtime to pip-installable package and add CLI?

### ISSUE THREAD

**Issue by rprimet** [CatalaLang/catala#245]
Looking at the catala repo, I wonder if it would be worth extracting the python runtime (`catala.py`) to a `pip`-installable package (since it's not related to french law) and optionnally provide a generic CLI utility that would let one call a given scope with arguments? (i.e. a generic version of `main.py`)?

Rationale: this would make it easier getting started with using the python backend with arbitrary catala programs by reducing the boilerplate needed to drive the generated code

**Comment by denismerigoux** [comment]
Thanks for your proposals ! Indeed that would be nice to have a `pip` package for `catala.py` to distribute it easily, and another one for `french_law` that depends on `catala`. 

I wonder what CLI you have in mind for this sort of Python interpreter you're describing : how would you pass the arguments ? It seems a bit redundant with the `Interpret` mode of the Catala compiler that would be preferable to use since it already has all the features that you would have to reimplement in Python. The rationale for the Python backend is really to be embedded into your larger Python app.

The boilerplate you might want to reduce is not in `main.py` but rather in `api.py` where we wrap the functions with the right converters between Python native types and Catala values. This wrapper could be auto-generated by the Catala compiler.

**Comment by denismerigoux** [comment]
This has been fixed by #246
