### ISSUE TITLE
`french_law/python/src/allocations_familiales.py` is checked in git

### ISSUE THREAD

**Issue by rprimet** [CatalaLang/catala#247]
Is it by design? Since it's auto-generated, it might be better to avoid checking this file into version control?

**Comment by denismerigoux** [comment]
It's by design because there is no automated distribution of the Python `french_law` package currently: if people just want to use the package I would tell them to just clone the repo and the fact that  `french_law/python/src/allocations_familiales.py` is checked means they don't have to install OCaml and so on to re-generate it.

**Comment by rprimet** [comment]
OK, closing this, we can maybe revisit if #246 lands
