### ISSUE TITLE
Cannot run examples

### ISSUE THREAD

**Issue by luisivan** [CatalaLang/catala#316]
Hi all!

Been trying to put in effort to try Catala out without much luck.
After following the docs, installing Catala, cloning this repo and executing `make -C examples/smic smic.html`, this is all I'm getting (which is weird because that file *does* exist):
<img width="532" alt="Screen Shot 2022-08-13 at 6 00 07 PM" src="https://user-images.githubusercontent.com/718208/184503717-e90bc7b1-7fb7-440b-84e1-5dc29c39ebaf.png">

Also FYI I had to manually change the executable reference in `examples/Makefile.common.mk` since it just points to an `.exe` file and I'm running it on Linux.

Executing a file just by doing `catala Interpret file.catala_en -s Scope` also throws an error, and I couldn't find anywhere in the docs how to do what it says:
<img width="566" alt="Screen Shot 2022-08-13 at 6 03 02 PM" src="https://user-images.githubusercontent.com/718208/184503789-161181b8-83cc-4e9b-93a0-52f56b17e728.png">

Thanks!

**Comment by AltGr** [comment]
> Also FYI I had to manually change the executable reference in examples/Makefile.common.mk since it just points to an .exe file and I'm running it on Linux.

The executable is expected to be `.exe` — the `dune` build system names executables like that internally for consistency across all OSes. I couldn't reproduce, did you run `make build` first ?

**Comment by luisivan** [comment]
Yes I did!

Regarding the *scope needs input arguments* error, do you happen to know how to create another scope that passes data to that scope, so I can run `Interpret`? Thanks

**Comment by denismerigoux** [comment]
Hi Luis, thanks for trying out Catala! Let's take your questions in order.

> After following the docs, installing Catala, cloning this repo and executing make -C examples/smic smic.html, this is all I'm getting (which is weird because that file does exist):
> Also FYI I had to manually change the executable reference in examples/Makefile.common.mk since it just points to an .exe file and I'm running it on Linux.

When you changed the executable reference contained in those lines of code:

https://github.com/CatalaLang/catala/blob/038e6068e6d321867f66805a3c0f364d5295c53e/examples/Makefile.common.mk#L9-L10

You probably axed away the `cd ../../;` at the beginning of the line. This change of directory before running the executable is necessary to have consistent relative file paths that all start from the root of the repository rather than an `examples/foo` directory. Because now the executable runs from inside `examples/foo`, it tries to find `examples/foo/examples/foo/file.catala_en`, which it cannot find because it should look for `examples/foo/file.catala_en` instead. 

To fix this problem, simply revert the changes you've made to the executable reference. As @AltGr said, it doesn't matter if it's a `.exe`, we all run Linux here and Linux doesn't care what is the extension of its executables.

> Regarding the scope needs input arguments error, do you happen to know how to create another scope that passes data to that scope, so I can run Interpret? Thanks

What are you trying to achieve here ? Just running any command to see a successful output? If so I suggest you run instead 

```
catala Python file.catala_en 
```

Which will produce a Python translation of the Catala program, stored by default in `file.py`. 

If you really want to interpret `file.catala_en`, then I think there's a semantic mismatch in the meaning of "interpreting". For us static-typing lovers, it means "executing" the program with inputs to produce an output. And since the scope `Scope` that you wanted to interpret leaves some inputs undetermined, you get an error message. If you come from a dynamically typed languages background and just want a sanity check that your program is okay syntactically, without executing it to get some output from an input, then you might just want to type in:

```
catala Typecheck file.catala_en -s Scope 
```

**Comment by luisivan** [comment]
Thanks a lot for the help @denismerigoux! I indeed axed `cd ../../;` and that was the issue :)

Now I'm stumbling upon this one: `Error: no lexer for alias 'catala_fr' found` which seems to be thrown by `pygmentize`.

Re/ `Interpret`: I still wanted to throw in some input data, just to see what would happen. What's the best way to do so?

**Comment by denismerigoux** [comment]
> Now I'm stumbling upon this one: Error: no lexer for alias 'catala_fr' found which seems to be thrown by pygmentize.

For this you need to do https://github.com/CatalaLang/catala/blob/master/INSTALL.md#pygments

> Re/ Interpret: I still wanted to throw in some input data, just to see what would happen. What's the best way to do so?

Let's say you have a Catala code like this:

```
declaration scope Foo:
  input x content integer
  ...
```
Then in the same file you can define another scope like this that will create the `x` input  data for `Foo` : 

```
declaration scope FooTest:
   foo scope Foo

scope FooTest
   definition foo.x equals 1
```

Now you can run `catala Interpret -s FooTest`. This is covered in [the tutorial](https://catala-lang.org/en/examples/tutorial#The%20Catala%20language%20tutorial-Testing%20Catala%20programs).

**Comment by luisivan** [comment]
Thanks a lot! 🙌
