### ISSUE TITLE
printing bug

### ISSUE THREAD

**Issue by adelaett** [CatalaLang/catala#454]
Related to #450 

Nested EInj
```
ESome Case1 ()
```

**Comment by adelaett** [comment]
Related to lists. There is the need for a hov box for list elements

```
[RESULT] y = ESome
           [ ESome
             0;
             ESome
             1;
             ESome
             2;
             ESome
             3;
             ESome
             4;
             ESome
             5;
             ESome
             6;
             ESome
             7;
             ESome
             8;
             ESome
             9;
             ESome
             10 ]
```

**Comment by AltGr** [comment]
```ocaml
ESome Case1 ()
```
There is no ambiguity here, esp. since we only have unary application and constructors.
But readability is a subjective thing, so feel free to propose changes — this ouput is primarily for our own consumption so let's use what's comfortable to us!

> Related to lists. There is the need for a hov box for list elements

hm indeed, even if the `hov` box could be disputed, the printing of the individual `ESome` arguments in the list is clearly wrong here (should not be a newline, and even in that case there should be an indentation step).
#420 claims to be a big improvement but is by no means perfect, feel free to propose PRs for such fixes and more improvements!
