### ISSUE TITLE
Move examples out of the repo (professionalize once 1.0 is out)

### ISSUE THREAD

**Issue by denismerigoux** [CatalaLang/catala#521]
The compiler repo should only contain :
* the compiler
* the language test suite
* the runtimes
* the plugins

Should be moved to another repo : 
* The French examples as well as the `french_law` package
* Other examples

**Comment by AltGr** [comment]
This will include a cleanup of the Makefiles, e.g. ensuring that `make build` builds everything that would be installed (i.e. `dune build @install`, which is what `make install` does at the moment), and that `make install` actually installs it to the prefix.

**Comment by AltGr** [comment]
I am starting work on this. Here is the plan:
- Create new `CatalaLang/catala-examples` repository containing the contents of the `examples` directory
- Create new `CatalaLang/french-law` repository containing the contents of the `french_law` directory
- Adjust doc and READMEs of these repositories ;
- Adjust installation of Catala and build rules so that the examples and API uses build correctly
  There will be a `catala`←`examples`←`french-law` dependency chain

Now for the CI: **all CI remains on the main Catala repository**
  (two reasons for that: these remain important tests for the compiler, and we don't want to scatter the test results or the build artifacts)
* Main catala CI: will build, test and install the compiler, then in another stage fetch the latest version of the examples / french law, build and check them, and publish their artifacts to https://catalalang.github.io/catala so that page will keep being updated as it is now
* Examples and french_law CI: the idea there is that upon update of master, the CI will do an API call to trigger a re-run of the main catala CI (that will fetch the newer version of the repo) ; this will ensure that the artifacts page is always up-to-date with both Catala and the examples/french-law repos.
* A specific CI for PRs on examples and french-law (that could use the published builds of the catala compiler ?) will probably be useful soon enough.

**Comment by AltGr** [comment]
Also: for now I intend to disable the bug-trackers on the two new repos, so that we keep all issues in the same place (the tracker of the main Catala repo)

**Comment by denismerigoux** [comment]
You plan looks good Louis ! And OK for disabling the bug trackers in the other examples. Do you think that you could extend your CI streak to cover update of the Catala websites `catala-website` and `catala-dfsr` too?
