### ISSUE TITLE
Continuation-based message module can lead to performance decrease

### ISSUE THREAD

**Issue by rmonat** [CatalaLang/catala#613]
The current `Message.debug` and its sibling implementations rely on the continuation-based `Format.kprintf`. Unfortunately, this means CPU time can be wasted in that part even if the debugging information are not enabled. This is significant in the concolic interpreter backend.

**Comment by denismerigoux** [comment]
Wouahou @AltGr I guess this could be easily solved. @rmonat I'm sorry for the hardcore debugging session that I can only imagine led you here...

**Comment by AltGr** [comment]
Oops indeed, my bad, I overlooked that we didn't actually use `ifprintf` as we should have in the `Message` module.
This should be fixed by https://github.com/CatalaLang/catala/pull/614/commits/c4c29a4a00e4eb288722224722f5e80a701c1ba0
(but see [here](https://github.com/CatalaLang/catala/pull/610) for more detailed considerations about the cost of `printf`)

**Comment by AltGr** [comment]
Glad to hear it! Sorry for having overlooked the issue to begin with :)
